# Generated by Django 4.2.7 on 2023-11-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('web', models.URLField(blank=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('rating', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('traffic', models.IntegerField()),
                ('scenery', models.FloatField()),
                ('comment', models.TextField(blank=True)),
                ('weather', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Venues',
                'ordering': ['name'],
            },
        ),
    ]
