# Generated by Django 4.2.7 on 2023-11-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_alter_venue_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='indoor',
        ),
        migrations.AddField(
            model_name='venue',
            name='category',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('hybrid', 'Hybrid')], default='outdoor', max_length=10),
            preserve_default=False,
        ),
    ]
