# Generated by Django 4.2.7 on 2023-11-05 00:22

from django.db import migrations, models
import venue.models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_remove_venue_indoor_venue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(upload_to=venue.models.upload_path),
        ),
        migrations.AlterField(
            model_name='venue',
            name='suitable_for',
            field=models.CharField(max_length=50),
        ),
    ]
