# Generated by Django 4.2.7 on 2023-11-05 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_alter_venue_image_alter_venue_suitable_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='traffic',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='VenueSurvey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('traffic', models.FloatField()),
                ('scenery', models.FloatField()),
                ('comment', models.TextField(blank=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue')),
            ],
            options={
                'verbose_name_plural': 'Venue Ratings',
                'ordering': ['venue'],
            },
        ),
    ]
